language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/simplePrinter/simplePrinter.ino PLATFORMIO_CI_EXTRA_ARGS="--board=d1_mini"
    - PLATFORMIO_CI_SRC=examples/simplePrinter/simplePrinter.ino PLATFORMIO_CI_EXTRA_ARGS="--board=lolin32"
    - CPPLINT=true

install:
    - pip install -U platformio
    - platformio lib -g install 306 64 1938
    - pip install -U cpplint

script:
    - if [[ "$CPPLINT" ]]; then cpplint --repository=. --recursive --linelength=200 --filter=-build/include  ./src; else platformio ci --lib="." --project-option="lib_ldf_mode=chain+" $PLATFORMIO_CI_EXTRA_ARGS; fi
